### ISSUE TITLE
mixup函数

### ISSUE THREAD

**Issue by ghost** [Yangget/garbage_classify#1]
**建议将其中的self.batch_size参数，修改为 batch_x.shape[0]。**
因为最后一个step可能不足batch_size的样本量，使用中报错。
修改如下：
        l = np.random.beta(alpha, alpha, batch_x.shape[0])
        X_l = l.reshape(batch_x.shape[0], 1, 1, 1)
        y_l = l.reshape(batch_x.shape[0], 1)
——————————————————————————————————
原代码：
        l = np.random.beta(alpha, alpha, self.batch_size)
        X_l = l.reshape(self.batch_size, 1, 1, 1)
        y_l = l.reshape(self.batch_size, 1)

**Comment by Yangget** [comment]
是的，因为我分割的数据量是8的幂次方，所以避开了这个问题。我在https://github.com/Yangget/Mixup_All-use/blob/master/Mixup.py    
重新写了这个地方。

**Comment by ghost** [comment]
ok.
